// File generated by Antigravity IDE for Firebase configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8cGo-Kcuu4Yv8OCx6SjD6W10eu3Ckcw',
    appId: '1:1007931970846:web:432b6ec47ededa8579e50f',
    messagingSenderId: '1007931970846',
    projectId: 'fireguard-safety-app',
    storageBucket: 'fireguard-safety-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy8cGo-Kcuu4Yv8OCx6SjD6W10eu3Ckcw',
    appId: '1:1007931970846:android:432b6ec47ededa8579e50f',
    messagingSenderId: '1007931970846',
    projectId: 'fireguard-safety-app',
    storageBucket: 'fireguard-safety-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8cGo-Kcuu4Yv8OCx6SjD6W10eu3Ckcw',
    appId: '1:1007931970846:ios:432b6ec47ededa8579e50f',
    messagingSenderId: '1007931970846',
    projectId: 'fireguard-safety-app',
    storageBucket: 'fireguard-safety-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy8cGo-Kcuu4Yv8OCx6SjD6W10eu3Ckcw',
    appId: '1:1007931970846:ios:432b6ec47ededa8579e50f',
    messagingSenderId: '1007931970846',
    projectId: 'fireguard-safety-app',
    storageBucket: 'fireguard-safety-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy8cGo-Kcuu4Yv8OCx6SjD6W10eu3Ckcw',
    appId: '1:1007931970846:web:432b6ec47ededa8579e50f',
    messagingSenderId: '1007931970846',
    projectId: 'fireguard-safety-app',
    storageBucket: 'fireguard-safety-app.firebasestorage.app',
  );
}
